### ISSUE TITLE
Fix this mongodb error that occurs when running the tests

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/web-jam-back#105]
This is from the tests ran locally
![image](https://cloud.githubusercontent.com/assets/13340120/26452122/b7a7ba6c-412c-11e7-877c-7953afc07990.png)

**Comment by JoshuaVSherman** [comment]
@LinuxBozo Maybe we can work on this on Sunday if you are available

**Comment by LinuxBozo** [comment]
The larger Circle error is all about not having an `.env` file. So to fix, do an "if exists" before the open.

**Comment by JoshuaVSherman** [comment]
@LinuxBozo thanks https://github.com/WebJamApps/web-jam-back/commit/5de20873445f0abe5db67eebd26b9bb120a14321
