### ISSUE TITLE
Write a backend unit test to cover the app.get function in index.js

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/web-jam-back#40]
![image](https://cloud.githubusercontent.com/assets/13340120/24815777/6deab59e-1ba4-11e7-8c0a-74acc5d24964.png)

**Comment by cesarodriguez4** [comment]
@JoshuaVSherman I guess the http response must be 200 for success, Am I right?

**Comment by JoshuaVSherman** [comment]
Seems correct to me
https://www.w3.org/Protocols/rfc2616/rfc2616-sec6.html

**Comment by JoshuaVSherman** [comment]
@cesarodriguez4 
Thanks, great job
