### ISSUE TITLE
update jest config for all active projects where needed (i did some already)

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/web-jam-back#441]
https://github.com/facebook/jest/issues/7136

@Unesdala yes after further reading, please make sure every jest.config.json includes
`"resetMocks": true`
https://jestjs.io/docs/en/configuration#resetmocks-boolean
and not "clearMocks"
* [ ] needed for appersonauto

**Comment by Unesdala** [comment]
Since the superagent mock is being reset, how do we call the it back into the tests we need it in?

**Comment by JoshuaVSherman** [comment]
Which project, college Lutheran?
Inside the /_mocks/superagent replace jest.fn with just ()=>
