### ISSUE TITLE
Create a valid Content-Security-Policy for Helmet

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/web-jam-back#473]
Currently disabled to fix, but we should re-enable it:

https://github.com/helmetjs/helmet/wiki/Helmet-4-upgrade-guide

The default policy breaks the page from loading directly to /music, this can be seen by running localhost:7000/music

If you run localhost:7000 and then navigate to /music there is no problem, however, we have a redirect from joshandmariamusic.com that goes directly to web-jam.com/music which makes this also an issue on production website.

**Comment by JoshuaVSherman** [comment]
@LinuxBozo do you think you could take a look at this and/or suggest a solution please?

**Comment by LinuxBozo** [comment]
Probably just need to provide something that's "good enough", which means a policy of `frame-ancestors 'self'`

**Comment by JoshuaVSherman** [comment]
@LinuxBozo I didn't realize that I needed to clear my browser history in between each attempt to change it, so after I figured that out, it was much easier to fix, this was the final solution:
```
app.use(helmet.contentSecurityPolicy({
  directives: {
    'default-src': ["'self'"],
    'base-uri': ["'self'"],
    'block-all-mixed-content': [],
    'font-src': ["'self'", 'https:', 'data:'],
    'frame-src': ["'self'", 'https://accounts.google.com'],
    'frame-ancestors': ["'self'"],
    'img-src': ["'self'", 'data:', 'https:'],
    'object-src': ["'none'"],
    'script-src': ["'self'", 'https://maps.googleapis.com', 'https://apis.google.com'],
    'script-src-attr': ["'none'"],
    'style-src': ["'self'", 'https:', "'unsafe-inline'"],
    'upgrade-insecure-requests': [],
    'connect-src': ["'self'", 'ws:', 'wss:'],
  },
}));
```
