### ISSUE TITLE
Support https://web-jam.com (use entrydns.net, maybe)

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/web-jam-back#58]
* https://web-jam.com
is currently not working
* https://www.web-jam.com
is working

I want both of them to work, not one or the other

**Comment by LinuxBozo** [comment]
@JoshuaVSherman So, this won't actually work with GoDaddy as the DNS server. You would have to use an alternative. I would say, something like entrydns.net

**Comment by JoshuaVSherman** [comment]
Oh well, thanks for trying

**Comment by LinuxBozo** [comment]
Let me investigate a bit more, but I may be able to make this work.

If not, you can actually keep your registration with godaddy (entrydns.net isn't a registrar) but use entrydns.net to manage the DNS records, and we can go over that.

**Comment by LinuxBozo** [comment]
This should now be working. GoDaddy is setup to point to entrydns.net nameservers, and entrydns.net now has the records required to make this work.
