### ISSUE TITLE
setup vscode on both computers and use some of these extensions

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/web-jam-back#610]
https://javascript.plainenglish.io/15-must-have-vs-code-extensions-for-web-developers-7d3d41a1165

**Comment by kathleenahall** [comment]
Latitude: installed auto rename tag for VS Code

**Comment by kathleenahall** [comment]
Latitude: install better comments

**Comment by chemmom2** [comment]
on MSI computer added: Auto Rename Tag, Better Comments, Color Highlight, Code Spell Checker, CodeSnap, Error Lens, Highlight Matching Tag, Turbo Console Log, TypeScript Error Translator
